### PR TITLE
[MSYS-678] Fix bug to catch error while chef-backup

### PR DESCRIPTION
**Pull request by NAshwini**
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>

### CODE REVIEW

**Comment by NimishaS** [comment]
@btm , please review.

**Review by stevendanna — APPROVED** [review]
Good catch!

**Comment by stevendanna** [comment]
I wonder if we also need to fix: https://github.com/chef/chef_backup/pull/28/files#diff-7b185048daf6de8237d6e46f76bd37c4R201

**Comment by NAshwini** [comment]
Thanks @stevendanna, yes will fix this https://github.com/chef/chef_backup/pull/28/files#diff-7b185048daf6de8237d6e46f76bd37c4R201 to avoid such type of error in future.

**Comment by btm** [comment]
@NAshwini are you going to push a change to this PR to update that call to `shell_out` as well?

**Comment by NAshwini** [comment]
yes @btm, fixed the PR as per review comments

**Review by btm — APPROVED** [review]

**Pull request merged**
